# Generated by Django 5.0.7 on 2024-08-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='atharva', max_length=100),
            preserve_default=False,
        ),
    ]
